version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pass2020!
      pgdata: /var/lib/postgresql/data
    name: dev-postgres
    volumes:
      - ~/postgres-data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.local
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    name: dev-pgadmin
    ports:
      - "80:80"
